run:
  timeout: 5m
linters:
  enable-all: true
  disable:
    # maligned # deprecated 1.38 but govet-fieldalignment not usuable
    - interfacer # deprecated 1.38
    - scopelint # deprecated 1.39
    - golint # deprecated 1.41
    - exhaustivestruct # deprecated 1.46
    # ifshort # deprecated 1.48 but no replacement
    - nosnakecase # deprecated 1.48.1
    - structcheck # deprecated 1.49.0
    - deadcode # deprecated 1.49.0
    - varcheck # deprecated 1.49.0
    - wsl
    - gochecknoglobals
    - gomnd
    - paralleltest
    - nonamedreturns
linters-settings:
  govet:
    enable-all: true
