run:
  timeout: 5m
linters:
  enable-all: true
  disable:
    # maligned # deprecated 1.38 but govet-fieldalignment not usuable
    - interfacer # deprecated 1.38
    - scopelint # deprecated 1.39
    - golint # deprecated 1.41
    - wsl
    - gochecknoglobals
    - gomnd
    - paralleltest
linters-settings:
  govet:
    enable-all: true
