name: Go Tests
on: [push, pull_request]
jobs:
  test-1_16:
    name: Test 1.16
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        id: go
      - name: Check out code
        uses: actions/checkout@v2
      - name: Test
        run: go test -v ./...

  test-1_17:
    name: Test 1.17
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v1
        with:
          go-version: 1.17
        id: go
      - name: Check out code
        uses: actions/checkout@v2
      - name: Test
        run: go test -v -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage.txt
