name: Go Tests
on: [push, pull_request]
jobs:
  test-1_15:
    name: Test 1.15
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v4
        with:
          go-version: '1.15'
        id: go
      - name: Check out code
        uses: actions/checkout@v4
      - name: Test
        run: go test -race -v ./...

  test-1_16:
    name: Test 1.16
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v4
        with:
          go-version: '1.16'
        id: go
      - name: Check out code
        uses: actions/checkout@v4
      - name: Test
        run: go test -race -v ./...

  test-1_17:
    name: Test 1.17
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v4
        with:
          go-version: '1.17'
        id: go
      - name: Check out code
        uses: actions/checkout@v4
      - name: Test
        run: go test -race -v ./...

  test-1_18:
    name: Test 1.18
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.18
        uses: actions/setup-go@v4
        with:
          go-version: '1.18'
        id: go
      - name: Check out code
        uses: actions/checkout@v4
      - name: Test
        run: go test -race -v ./...

  test-1_19:
    name: Test 1.19
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'
        id: go
      - name: Check out code
        uses: actions/checkout@v4
      - name: Test
        run: go test -race -v ./...

  test-1_20:
    name: Test 1.20
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
        id: go
      - name: Check out code
        uses: actions/checkout@v4
      - name: Test
        run: go test -race -v ./...

  test-1_21:
    name: Test 1.21
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
        id: go
      - name: Check out code
        uses: actions/checkout@v3
      - name: Test
        run: go test -race -v ./... -coverprofile=coverage.out -covermode=atomic

      - name: Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage.out
