name: Go Tests
on: [push, pull_request]
jobs:
  test:
    name: Test
    strategy:
      matrix:
        golang:
          - '1.15'
          - '1.16'
          - '1.17'
          - '1.18'
          - '1.19'
          - '1.20'
          - '1.21'
          - '1.22'
          - '1.23'
          - '1.24'
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go ${{ matrix.golang }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.golang }}
        id: go
      - name: Check out code
        uses: actions/checkout@v5
      - name: Test
        run: go test -race -v ./...

  test-latest:
    name: Test 1.25
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.25
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
        id: go
      - name: Check out code
        uses: actions/checkout@v5
      - name: Test
        run: go test -race -v ./... -coverprofile=coverage.out -covermode=atomic

      - name: Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.out
