name: GolangCI-Lint-Latest
on:
  push:
    branches:
      - main
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
          check-latest: true
        id: go
      - name: Check out code
        uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: -c .golangci.yml -v
